### ISSUE TITLE
Sprint 3 - Managing hosting

### ISSUE THREAD

**Issue by ipr17** [DeltaO3/UWAttend---3200_27#32]

**Comment by Ay1tsMe** [comment]
Current AWS EC2 instance is working with no permission issues being displayed anymore.
A `README` file is in the home directory of the server that explains how everything is being run.

Things that need to be fixed in the future:
1. DNS Records need to be set up by Adrian, so that users can connect to the web app through the URL rather than the IP address of the server
2. HTTPS using certbot needs to be set up instead of http
