### ISSUE TITLE
Sprint 3 - Research how to save information if no access to Internet

### ISSUE THREAD

**Issue by ipr17** [DeltaO3/UWAttend---3200_27#33]
Professor gives a high value to this so ensure it gets done. Save information while disconnected until the user presses sync, and then attempt to push to database.

**Comment by ozzy1323232** [comment]
I Wrote some javascript code that can successfully save data in offline mode, but its pointless, i dont think we need to implement this as:

- If we are offline (the server is offline not the internet) then we wouldnt be able to access the webapp anyway and also wouldnt be able to access the javascript that will save the offline data?? 

So this issue basically only applies to the situation where the webapp is connecting ok and the server is up but for like 5 minutes it randomly drops out then the client temporarily cant take attendance? then assuming that within the next 5 or 10 minutes ( because the client will be staying back in class waiting for the app to work) the server suddenly starts working?

**Comment by DeltaO3** [comment]
Definitely to be asked of client

**Comment by DeltaO3** [comment]
Out of scope now ?
