### ISSUE TITLE
Sprint 2 - Research/implement API to grab central time

### ISSUE THREAD

**Issue by DeltaO3** [DeltaO3/UWAttend---3200_27#43]
This should be implemented in place of the current time function on /session.

**Comment by Ay1tsMe** [comment]
Use this for ntp server: https://www.ntppool.org/en/

**Comment by Ay1tsMe** [comment]
just did a bit of research and the current `datetime` module that is retrieving the date and time for the session is currently grabbing the data from the servers machine. I initially thought that it was displaying the date and time from the users system clock, not the servers system clock. 

Is it necessary then to use a NTP server to retrieve the date and time or can we rely whatever server is hosting the code the have the correct date and time?

**Comment by ipr17** [comment]
I think it will be enough to just rely on the server, but if it's not too difficult it may be worth getting the date externally, as I think that's what people seemed to want in the last meeting. Maybe if you do some research and it seems like it will take a lot of time to implement and so not be worth it, then just use datetime, but if not then it might be good to have that extra assurance that the times are correct. 
Also hard to know since we don't know how we will be hosting this webapp.

**Comment by DeltaO3** [comment]
Didn't realise that was the case, if its server based I'm willing to table this issue for now! Up to you, I think server based is sufficient (can make it a sprint 3 optional extension goal?)

**Comment by Ay1tsMe** [comment]
I think it's sufficient to rely on server time. In practice, the server should be linked to a NTP anyway. 

Although going to account for if the server is not in the location of UWA
