### ISSUE TITLE
Sprint 2 - Login functionality

### ISSUE THREAD

**Issue by DeltaO3** [DeltaO3/UWAttend---3200_27#46]
Make login work as intended - redirect if not logged in, make sure only admin can access admin (if possilbe? optional for now)

**Comment by livvy10** [comment]
so I think Delta was intending me to do this one but I realise I didn't assign it so all good, just some clarifications for what this issue is about:
- implementing UserMixin in models so that pre-made functions can be used
- if a user tries to access other pages (e.g. home page) but they are not logged in, they should be redirected to the login page. this can easily be implemented by using login_required on all routes that should only be accessible to logged in users
- set_password and check_password functions in User class definition in models.py
- using login_user and logout_user to add functionality

**Comment by livvy10** [comment]
To do after models.py has been set up

**Comment by livvy10** [comment]
https://blog.miguelgrinberg.com/post/the-flask-mega-tutorial-part-v-user-logins basically explains all the necessary things we want done for this issue
