### ISSUE TITLE
Sprint 1 - Stories

### ISSUE THREAD

**Issue by DeltaO3** [DeltaO3/UWAttend---3200_27#5]
From the CITS3200 site:

>A set of [stories](https://www.atlassian.com/agile/project-management/epics-stories-themes) to be completed in Sprint 2. It is recommended that you also create a set of intermediate acceptance criteria to assess the products of that Sprint for your internal use, but these will not assessed.

**Comment by livvy10** [comment]
Here is my feedback on the user stories so far.

I really like the format so that it includes the person, what they want to do, and why.

From my understanding, user stories are meant to be quite simple. I think it would be simpler and easier to understand if each one was broken down into the different things the users wanted to do (I think having multiple with the same user is fine and would make it clearer - though if someone else can comment on this as this is just my opinion).

This is from https://www.atlassian.com/agile/project-management/user-stories which might be useful to look at:

![image](https://github.com/user-attachments/assets/1b51659f-8e62-4a61-8d32-a279e2984240)
![image](https://github.com/user-attachments/assets/f238d1cd-4e90-4f27-b0b0-7cfc85f4d1ed)


Also I think that considering user stories are meant to prioritise the user's perspective, I think technical language should be avoided (e.g. avoid "CRUD" and "cryptographically secure", and instead write "insert/view/update/delete data" and "transmit the files and information safely" or "ensure private info is kept private").
