### ISSUE TITLE
Sprint 2 - Create models.py

### ISSUE THREAD

**Issue by DeltaO3** [DeltaO3/UWAttend---3200_27#62]
Using olivia's new models, create a models.py. Update the readme as necessary, update the requirements.txt as necessary.

**Comment by livvy10** [comment]
I started to draft an email to Adrian to discuss what he wants for session times (aka session occurrence), however I realised that I had so many questions and different things have different trade-offs and it was going to be too difficult, so after some thinking and after our discussion after the meeting on Friday, I've just picked option 1 (the same as I had done in the database schema design draft).

First thing to note is that we definitely need a session time so that we can identify a session correctly, so if multiple facilitators are signing in students to the same session, we can ensure that they can see all the students, and also if session details need to be changed (e.g. session name is wrong) then we can change it for all the attendances for a given session more easily.

Option 1

Option 1 is the unit coordinator configures the unit at the beginning and for session times, just selects from a list of pre-defined session times, e.g. Morning, Afternoon, 10AM-11AM, Full Day, 1PM-3PM (and many more variations. this list would be long to support all units needs with varying session lengths and start times but we can use javascript to make it a nicer user experience e.g. typing in to narrow down options and then clicking on an option to add.).

When a facilitator goes to configure a session, they click the session name and the session time available for that unit (as configured by unit coordinator at the beginning of sem). All combinations of name and time are valid. Based on the current time, a session time is suggested for them (or alternatively, is already picked for them but they can change it if they want). After starting a session and signing in students, towards the end of session time, there will be smart prompts to sync the data, to finish the session etc. as the session is finishing soon, or potentially if they try to sign in a student towards the end of a lesson, there is a warning to double check they are intending to sign in a student to this session, rather than the next session. We can also do a smart prompt that when they press sync, if the current time doesn't match the session time that they have selected (e.g. the session time is Morning or 11AM-12PM and it is currently 3PM) then we can specifically say to double check (as well as a more generic reminder to check all details). Basically - as the values are pre-defined, we can do smart prompts and suggestions as Adrian has said he wanted. In the future there could be support for user-defined session times.

Strengths and limitations of Option 1: less work and fairly easy for unit coordinator to set up, flexibility with adding a session any time without unit coordinators needing to change anything (as all sessions can be run at any possible session time). Limitations are that facilitators are more trusted (and could do more wrong) as any time can be picked for any sessions (even if sessions are not meant to be running at certain times), and also unit coordinators have to pick from a pre-defined list (although hopefully our list can be fairly exhaustive).

Option 2

Option 2 is to have the unit coordinator give additional details about each type of session. E.g. Pipeworks is run every Monday at 3pm-4pm, Wednesday 2pm-3pm etc. (so on Mondays, only 3pm-4pm shows up on facilitator's session config). Or even just, Pipeworks is only ever run at 2pm-3pm and 3pm-4pm. In either case, the session times available to the facilitator are limited on a per-session basis. The same smart suggestions and smart prompts could be implemented as in option 1.

Alternatively we could do something where each session name has an associated length of time which the unit coordinator specifies during unit config (e.g. Pipeworks goes for 1hr, CAD goes for 2hr). And then session times are available either to all sessions (like option 1), or to each session individually as specified by unit coordinator (like option 2), but the session times are only start times, e.g. 11am, 12pm. Or I suppose Morning and afternoon (but that start making it a bit icky - still doable though). Smart prompts and smart suggestions are based on the start time selected and the session length. I personally like this one, assuming sessions having a fairly predictable session length (which I suppose is also somewhat assumed in any of the other ways I've mentioned). 

Regardless of what we choose, this additional data would of course need to be stored in the database in a new table.

Strengths and limitations of Option 2: more work for unit coordinator to set up (e.g. if they have to go for each session and specify all the times it can be - although unit config should only happen once), less flexibility to add a session randomly at a different time (e.g. if a session usually runs on Monday and Wednesday afternoon, but they need to quickly do another session just once on Thursday arvo, then the unit coordinator would have to update it in the unit config to add this session time to the session). And again, unit coordinators have to pick from a pre-defined list (although hopefully our list can be fairly exhaustive)  - although we could have a time option where they can choose any start time potentially. Pros are that the facilitator is less likely to make a mistake as they have less incorrect options available. 

The way I have chosen (option 1) is definitely able to make the minimal viable product, meanwhile option 2 has many different ways we could do it that would also need client verification, so I decided instead of trying to make a more complex one and make decision myself, I would just go with option 1.
