### ISSUE TITLE
Sprint 3 - Improve CSV export logic

### ISSUE THREAD

**Issue by DeltaO3** [DeltaO3/UWAttend---3200_27#92]
Client mainly wants the CSV to effectively display a modified/formatted version of the attendance file. May wish to enquire as to the exact specifics for this.

**Comment by Ay1tsMe** [comment]
Client wants the following:
- Create another CSV file called `attendancerecordsCOLUMNS.csv` that is formatted similar to the MockDatabase. Instead of each row an entry for attendance, each row should be a student with each column being an attendance record.
- Double-check row headers are the EXACT same as the MockDatabase. Adrian uses this for LMS grade uploads.

**Comment by Ay1tsMe** [comment]
https://github.com/DeltaO3/UWAttend---3200_27/pull/141
